### ISSUE TITLE
Arthur Costa Lopes, Diego F Aranha. Platform-agnostic Low-intrusion Optical Data Exfiltration

### ISSUE THREAD

**Issue by dpetruh** [almkuznetsov/bmstu-kb#56]
Скрытый Канал утечки оптической информации за счет мигания диодов со съемом с помощью фото/видео съемки.

Источник информации: диоды на USB-носителе, которые передают небольшого объема информацию за счет их побитного мигания.

Принцип работы: как только необходимая информация попадает на флэш-накопитель, диоды начинают мигать согласно передаваемым битам информации.

Способ перехвата: камера с высокой частотой записи кадров снимает мигание диодов, далее проходит расшифровка полученных данных

**Comment by almkuznetsov** [comment]
Мне кажется опять же как и в #52 и #53 изначально утекает телекоммуникационная информация - ее просто потом кодируют и передают с помощью оптики

**Comment by almkuznetsov** [comment]
Добавил к каналу утечки телекоммуникационной информации за счет программного управления компонентами основных технических средств и систем с приемом информации из оптически-прозрачной среды в видимом диапазоне
