### ISSUE TITLE
Mordechai Guri, Andrey Daidakulov, Yuval Elovici. MAGNETO: Covert Channel between Air-Gapped  Systems and Nearby Smartphones via CPU-Generated Magnetic Fields. 

### ISSUE THREAD

**Issue by nedomolkinaeyu** [almkuznetsov/bmstu-kb#58]

**Comment by nedomolkinaeyu** [comment]
Скрытый канал между системами, находящимися в воздушной прослойке, и смартфонами поблизости с помощью магнитных полей, генерируемых процессором.

В этой статье показывается, что злоумышленники могут передавать данные с изолированных компьютеров, находящихся в воздушном пространстве, на близлежащие смартфоны с помощью скрытых магнитных сигналов. 
Для утечки данных со взломанного компьютера с воздушным зазором без сети злоумышленники должны пропустить данные через специальные типы скрытых каналов, известные как скрытые каналы с воздушным зазором. 
В данной статье мы предлагается магнитный скрытый канал между компьютерами с воздушной прослойкой (например,
рабочей станцией) и смартфоном, расположенным поблизости. Отметим, что для работы скрытого канала необходимо, чтобы вредоносный код был запущен на обеих сторонах: на компьютере с воздушной защитой и на соседнем смартфоне.
Скрытые каналы воздушного зазора можно разделить на пять основных категорий: электромагнитные, магнитные, акустические, тепловые и оптические.
Модель атаки состоит из трех этапов: заражение сети с воздушными зазорами, заражение смартфона и эксфильтрация данных.
На первом этапе заражается один узел в сети с воздушным захватом, возможно, через съемный носитель, стороннее программное обеспечение или аппаратные компоненты. 
На втором этапе определяется местонахождение смартфона сотрудника, на который направлена атака, и на него устанавливается приложение-приемник.
Когда первые два шага выполнены, атака переходит в фазу эксфильтрации.
ПЕРЕДАЧА.
Движущиеся заряды в проводе создают магнитное поле.
Магнитное поле изменяется в зависимости от ускорения зарядов в проводе. В стандартном компьютере провода, по которым электричество поступает от основного источника питания к материнской плате, являются основным источником магнитной эманации. Центральный процессор является одним из крупнейших потребителей энергии в материнской плате. 
МЕРЫ ПРОТИВОДЕЙСТВИЯ.
Обнаружением скрытых каналов могут заниматься системы безопасности, работающие на компьютере или смартфоне. При таком подходе решения безопасности постоянно отслеживают действия процессов и пытаются обнаружить вредоносные операции. В случае предлагаемого магнитного скрытого канала подозрительным считается поток (или группа потоков), который манипулирует рабочей нагрузкой процессора. 
ПРОФИЛАКТИКА.
Существует три различных подхода, которые могут быть использованы для предотвращения установления злоумышленниками предлагаемого магнитного скрытого канала: экранирование, глушение и зонирование.

ИТОГИ
Результаты показывают, что скрытый канал эффективен на небольших расстояниях (12,5 см) и работает на низкой скорости передачи данных (<5 бит/сек). Однако скрытый канал эффективен в ограниченных условиях, когда все беспроводные коммуникации заблокированы, например, когда смартфон хранится в мешке Фарадея или настроен на авиарежим.

**Comment by almkuznetsov** [comment]
Как можно сформулировать название скрытого канала?

**Comment by dpetruh** [comment]
Как можно
видеть, сила магнитного сигнала значительно уменьшается
с увеличением расстояния. На расстоянии 0 см (левая ось Y)
смартфон принимает сигналы на уровне ~109,7 мкТл (в
среднем), в то время как уровни фонового шума составляют ~108.5µT.At
на этом расстоянии уровень SNR составляет 14,902дБ. Для расстояний 5 см,
10 см и 15 см (правая ось Y) уровни SNR равны
17,879дБ, 12,420 дБ и 10,240дБ соответственно. На
расстоянии более 15 см уровни фонового шума были сильнее
чем у сигнала; поэтому мы прекратили проводить
измерения на расстоянии 15 см. Обратите внимание, что SNR
, измеренный с близкого расстояния (0 см), ниже, чем SNR
, измеренный с расстояния 5 см. Более низкий SNR при 0 см обусловлен другими
магнитными полями, исходящими от компьютера (например, от источника
питания), которые создают помехи нашему сигналу.

**Comment by dpetruh** [comment]
Мы измерили частоту битовых ошибок (BER) скрытого канала для
расстояний в диапазоне от 0 до 15 см между передающим
компьютером (ПК) и смартфоном. Для измерений BER
мы использовали простую модуляцию OWK. Наши тесты включают три
скорости передачи: 0,2 бит/сек, 1 бит/сек и 5 бит/сек.
Результаты приведены в таблице 6.

**Comment by almkuznetsov** [comment]
Добавил к каналу утечки телекоммуникационной информации за счет программного управления компонентами основных технических средств и систем и побочных электромагнитных излучений с приемом информации бесконтактно из диэлектрической воздушной среды
