### ISSUE TITLE
Mordechai Guri, Boris Zadov, Dima Bykhovsky, Yuval Elovici. CTRL-ALT-LED: Leaking Data from AirGapped Computers via Keyboard LEDs. 2019 IEEE 43rd Annual Computer Software and Applications  Conference (COMPSAC), 2019. P. 801-810

### ISSUE THREAD

**Issue by nedomolkinaeyu** [almkuznetsov/bmstu-kb#59]

**Comment by nedomolkinaeyu** [comment]
Использование светодиодов клавиатуры для оптической передачи данных было предложено в 2002 году Лоури и Умфрессом. В этой статье исследуется эта угроза в контексте современной кибератаки с использованием современного аппаратного и оптического оборудования. В этом типе атаки расширенная постоянная угроза (APT) использует светодиоды клавиатуры (Caps-Lock, Num-Lock и Scroll-Lock) для кодирования информации и оптического извлечения данных с компьютеров с воздушным доступом. 
Скрытые каналы с воздушным зазором можно разделить на электромагнитные, магнитные, акустические, тепловые и оптические каналы.
Далее приводится информация по всем этим каналам по отдельности.
Как и в случае со скрытыми каналами с воздушным зазором, модель состязательной атаки состоит из двух вредоносных компонентов: передатчика и приемника.
Передатчик представляет собой настольный компьютер или сервер, подключенный к клавиатуре через USB-порт, либо напрямую, либо через USB-концентратор или KVM. Компьютер должен быть заражен вредоносной программой, которая собирает конфиденциальные данные с компьютера пользователя (например, нажатия клавиш, пароль, ключи шифрования, документы). 
Приемник представляет собой часть оптического оборудования, которое имеет прямой обзор светодиодной панели клавиатуры. Существует несколько типов оборудования, которое может использоваться для приема в этой модели атаки. Приемник может быть скрытой камерой, которая находится в прямой видимости от передающих клавиатур, камерой высокого разрешения, расположенной снаружи здания, но расположенной так, чтобы она была в прямой видимости от передающих клавиатур, или телевизионной или IP-камерой с замкнутым контуром видеонаблюдения, расположенной в месте, где у нее есть прямая видимость.прямая видимость передающих клавиатур. Приемник также может быть смартфоном или носимой видеокамерой (например, умными часами), находящейся у злоумышленника, который может позиционировать себя так, чтобы иметь прямой обзор передающих клавиатур, сценарий, известный как атака ’злой горничной’.
Далее есть рисунок 1.2, где приведена иллюстрация этой атаки.
![image](https://user-images.githubusercontent.com/106398080/209568049-1b8d9d12-1f12-4b81-bc3a-b9c71cd48c2d.png)
![image](https://user-images.githubusercontent.com/106398080/209568070-f7a6efc4-1617-4066-92ed-b0c5be3df94b.png)

1) Приемники камер.
Существует два типа приемников, соответствующих модели атаки: камеры и датчики освещенности. Получение оптических сигналов камерой зависит от прямой видимости и видимости клавиатуры. 
2) Приемники датчиков освещенности.
Фотодиод - это полупроводник, который преобразует свет в электрический ток. Для оценки передач на высоких скоростях мы построили измерительную установку на основе фотодиодных датчиков освещенности.

КОНТРМЕРЫ.
Общие контрмеры могут включать политики, направленные на ограничение доступа к чувствительному оборудованию путем размещения его в закрытых помещениях, где доступ к нему имеет только авторизованный персонал. Как правило, все типы камер (включая смартфоны и умные часы) запрещены в таких защищенных помещениях. Однако запрет камер не всегда осуществим, поскольку наличие камер безопасности и наблюдения также может служить сдерживающей мерой. Еще одна превентивная контрмера - отключить светодиоды клавиатуры на уровне схемы или закрыть их.
Другой подход заключается в прерывании излучаемых сигналов путем преднамеренного вызова случайного мигания светодиодов. 

ИТОГИ
Данные могут передаваться с компьютеров с воздушным зазором через светодиоды клавиатуры со скоростью передачи 3000 бит / с на светодиод при использовании датчика освещенности в качестве приемника и более 120 бит / с, если используется камера смартфона.

**Comment by almkuznetsov** [comment]
Как можно сформулировать название скрытого канала?

**Comment by almkuznetsov** [comment]
Добавил к каналу утечки телекоммуникационной информации за счет программного управления компонентами основных технических средств и систем с приемом информации из оптически-прозрачной среды в видимом диапазоне
