### ISSUE TITLE
Mordechai Guri, Boris Zadov, Andrey Daidakulov, Yuval Elovici. xLED: Covert Data Exfiltration from  Air-Gapped Networks via Switch and Router LEDs

### ISSUE THREAD

**Issue by nedomolkinaeyu** [almkuznetsov/bmstu-kb#60]

**Comment by nedomolkinaeyu** [comment]
Скрытая утечка данных из воздушных сетей через светодиоды маршрутизатора.

Показывается, как злоумышленники могут скрытно утекать данные (например, ключи шифрования, пароли и файлы) из высокозащищенных или воздушных сетей через ряд светодиодов состояния, которые имеются в сетевом оборудовании, таком как коммутаторы локальной сети и маршрутизаторы. 
В этой статье исследуется угроза утечки данных из сетей с воздушной завесой через ряд светодиодов, которые имеются в сетевом оборудовании, таком как коммутаторы и маршрутизаторы.
Как и типичный скрытый канал, наша модель атаки противника состоит из передатчика и приемника. В нашем случае передатчиком является сетевой коммутатор или маршрутизатор, через светодиоды которого происходит утечка данных. Приемник - это удаленная камера или оптический датчик, который регистрирует сигналы светодиодов. 
Передатчик.
В рамках модели атаки злоумышленник должен выполнить вредоносный код в целевом маршрутизаторе, чтобы получить возможность управлять светодиодными индикаторами состояния. Мы представляем два типа атак, которые могут быть использованы для этой цели: (1) модификация микропрограммы маршрутизатора и (2) выполнение вредоносного скрипта или шеллкода на немодифицированном маршрутизаторе.
Приемник - это цифровая камера или оптический датчик, который находится в прямой видимости со светодиодной
панелью скомпрометированного маршрутизатора. Существует несколько типов оборудования, которое может играть роль приемника в данной модели атаки: (1) скрытая камера, имеющая прямую видимость на передающий маршрутизатор, (2) камера высокого разрешения, расположенная вне здания, но размещенная так, чтобы иметь прямую видимость на передающий маршрутизатор, (3) видеоприемник.
Для оценки скрытого канала был реализован передатчик для операционной системы OpenWrt. OpenWrt - это
ОС с открытым исходным кодом на базе Linux, используемая на встраиваемых устройствах, таких как маршрутизаторы, шлюзы и карманные устройства. Она поддерживает множество типов маршрутизаторов от широкого круга производителей, включая Cisco, Linksys, D-Link и других.
Предотвращение и обнаружение - это два основных типа контрмер, направленных на борьбу с утечкой данных на основе эманации.

ИТОГИ
Сетевые устройства (например, коммутаторы и маршрутизаторы локальной сети) обычно включают светодиодные индикаторы активности и состояния различных размеров и цветов. Такие светодиоды используются для мониторинга активности трафика, оповещения в случае аппаратных или программных сбоев, тестирования устройства и так далее. Показано, что эти светодиоды могут управляться вредоносным кодом, запущенным на устройстве. В типичной модели атаки данные, такие как файлы, ключи шифрования и данные о прослушивании клавиатуры, кодируются и модулируются через мигание светодиодов.
Данные могут быть удалены из сети с воздушной защитой через светодиоды коммутаторов и маршрутизаторов со скоростью передачи от десятков до тысяч бит в секунду на один светодиод, в зависимости от типа приемника и количества используемых светодиодов.

**Comment by almkuznetsov** [comment]
Как можно сформулировать название скрытого канала?

**Comment by almkuznetsov** [comment]
Добавил к каналу утечки телекоммуникационной информации за счет программного управления компонентами основных технических средств и систем с приемом информации из оптически-прозрачной среды в видимом диапазоне
