### ISSUE TITLE
Mordechai Guri, Boris Zadov, Yuval Elovici. LED-it-GO: Leaking (A Lot of) Data from Air-Gapped  Computers via the (Small) Hard Drive LED. DIMVA 2017. Detection of Intrusions and Malware, and  18 ВЕСТНИК УрФО. БЕЗОПАСНОСТЬ В ИНФОРМАЦИОННОЙ СФЕРЕ № 4(38) / 2020 Vulnerability Assess-ment

### ISSUE THREAD

**Issue by nedomolkinaeyu** [almkuznetsov/bmstu-kb#61]

**Comment by nedomolkinaeyu** [comment]
Утечка (большого количества) данных из герметичных компьютеров через (маленький) светодиод жесткого диска.

В этой статье представлен метод, позволяющий злоумышленникам скрытно передавать данные с изолированных компьютеров, защищенных от проникновения воздуха. Данный метод использует светодиодный индикатор активности жесткого диска (HDD), который имеется в большинстве современных настольных ПК, ноутбуков и серверов. Показано, что вредоносная программа может косвенно управлять светодиодом жесткого диска, быстро включая и выключая его (до 5800 миганий в секунду) - скорость, превышающая возможности визуального восприятия человека.

Метод, представленный в данной статье, имеет два основных преимущества по сравнению с другими методами на основе светодиодов: скрытность и скорость.
Состояние светодиодов питания клавиатуры и экрана часто меняется, и, скорее всего, любое мигание, вызванное вмешательством в этот канал, будет очевидно для наблюдателей. С другой стороны, светодиод активности жесткого диска мигает часто (из-за фоновых операций ОС), и, следовательно, эффекты коммуникации по этому
каналу (изменения в частоте мигания) не привлекут внимания.

Модель атаки состоит из двух этапов: (1) заражение целевого компьютера вредоносной программой и (2) прием и декодирование сигналов, просочившихся через светодиод HDD.

Существует несколько типов оборудования, которое может играть роль приемника в этой
модели атаки.
• Локальная скрытая камера. Скрытая камера, имеющая прямую видимость на переднюю панель передающего компьютера.
• Удаленная камера высокого разрешения. Камера высокого разрешения (или другой тип оптического датчика), которая находится вне здания, но расположена так, что имеет прямую видимость с передней панелью передающего компьютера.
• Камера дрона. Камера, установленная на универсальном дроне, который летит в место, имеющее прямую видимость с передней панелью передающего компьютера, например, возле окна.

Экспериментальная установка состоит из трех готовых стандартных настольных ПК, каждый из которых оснащен светодиодным индикатором HDD разного типа.
Обратите внимание, что хотя большинство светодиодов индикации жесткого диска имеют красный цвет, многие производители сегодня используют другие цвета. Для оценки мы использовали красный, синий и белый типы светодиодов HDD.

Меры противодействия утечке данных на основе эманации можно разделить на процедурные и технологические.

**Comment by almkuznetsov** [comment]
Как можно сформулировать название скрытого канала?

**Comment by almkuznetsov** [comment]
Добавил к каналу утечки телекоммуникационной информации за счет программного управления компонентами основных технических средств и систем с приемом информации из оптически-прозрачной среды в видимом диапазоне
