### ISSUE TITLE
Mordechai Guri, Yosef Solewicz, Andrey Daidakulov, Yuval Elovici. DiskFiltration: Data Exfiltration  from Speakerless Air-Gapped Computers via Covert Hard Drive Noise

### ISSUE THREAD

**Issue by nedomolkinaeyu** [almkuznetsov/bmstu-kb#62]

**Comment by nedomolkinaeyu** [comment]
Исчезновение данных с компьютеров без динамиков с воздушным затвором через скрытый шум жесткого диска.

В этой статье представляется "DiskFiltration", скрытый канал, который облегчает утечку данных с компьютера, находящегося в воздушной прослойке, с помощью акустических сигналов, излучаемых жестким диском (HDD).

Вредоносная программа, установленная на взломанном компьютере, может генерировать акустические излучения на определенных звуковых частотах, управляя движениями рычага привода жесткого диска.

Данный метод основан на акустических сигналах, генерируемых механическими частями жесткого диска, и поэтому применим к HDD и SSHD, а не к SSD.

Атакующая модель
DiskFiltration, как акустический скрытый канал, может быть использован для утечки данных с компьютеров, находящихся в воздушном пространстве. Однако этот скрытый канал также может быть использован в случае компьютеров, подключенных к Интернету (не воздушных), в которых сетевой трафик интенсивно контролируется сетевыми системами обнаружения вторжений (IDS), предотвращения вторжений (IPS) и предотвращения утечки данных (DLP). В этих случаях утечка данных через интернет трафик может быть обнаружена, и поэтому злоумышленник может захотеть прибегнуть к внеполосному скрытому каналу.

Модель состязательной атаки состоит из передатчика и приемника. Передатчиком обычно является обычный настольный компьютер или сервер, на котором установлен как минимум один жесткий диск. Приемник - это находящееся поблизости устройство с возможностью записи звука. Это может быть смартфон, положенный на стол, смартчасы на руке пользователя или находящийся рядом ноутбук с микрофоном.

Меры противодействия атаке DiskFiltration можно разделить на три категории: аппаратные, программные и процедурные

Аппаратные контрмеры. 
Замена жестких дисков на твердотельные накопители может устранить угрозу, поскольку твердотельные накопители не являются механическими и, следовательно, практически не создают шума.

Программные контрмеры. 
На уровне программного обеспечения и прошивки современные жесткие диски включают функцию автоматического управления акустикой (AAM), которая уменьшает акустический шум при поиске. 

Контрмеры, основанные на процедурах. 
Процедурные контрмеры предполагают физическое отделение излучающего оборудования от потенциальных приемников. 

ИТОГИ
В данной работе представляется новый тип акустического внеполосного скрытого канала под кодовым названием DiskFiltration. В этом методе злоумышленник может передавать двоичные данные с компьютеров через скрытые шумы, исходящие от жестких дисков. Скрытые сигналы могут быть приняты находящимся поблизости записывающим устройством, таким как смартфон, смартчасы, ноутбук и т. д. 
Несмотря на общий вклад DiskFiltration в область скрытых каналов, она особенно актуальна в двух враждебных сценариях: (1) в сетях с воздушной защитой, где нет сетевого соединения между компьютером и Интернетом, и (2) в компьютерах с сильно контролируемыми (системами IDS и IPS) интернет соединениями.
о DiskFiltration может использоваться для скрытой
передачи данных на расстояние до двух метров (шести футов) от передающего
компьютера при скорости передачи 180 бит/мин (10 800 бит/час).

**Comment by almkuznetsov** [comment]
Как можно сформулировать название скрытого канала?

**Comment by almkuznetsov** [comment]
Добавил к каналу утечки телекоммуникационной информации за счет программного управления компонентами основных технических средств и систем с приемом акустической информации из воздушной среды
