### ISSUE TITLE
Mordechai Guri, Yosef Solewicz, Andrey Daidakulov, Yuval Elovici. Fansmitter: Acoustic data  exfiltration from (speakerless) air-gapped computers

### ISSUE THREAD

**Issue by nedomolkinaeyu** [almkuznetsov/bmstu-kb#63]

**Comment by nedomolkinaeyu** [comment]
В этой статье представляется Фансмиттер, вредоносное ПО, которое может акустически извлекать данные из
компьютеров с воздушным зазором, даже если звуковое оборудование и динамики отсутствуют. В методе используется шум, издаваемый процессором и вентиляторами корпуса, которые сегодня присутствуют практически в каждом компьютере. 

Модель атаки
Хотя Fansmitter вносит общий вклад в область акустических скрытых каналов, как и другие работы, которые представляют внеполосные скрытые каналы, мы предлагаем Fansmitter как метод извлечения информации из компьютеров с воздушным зазором. . Подобно другим скрытым каналам связи, модель состязательной атаки состоит из передатчика и приемника. Как правило, в наших сценариях передатчиком является обычный настольный компьютер, а приемником — ближайший мобильный телефон. На предварительном этапе злоумышленник мог скомпрометировать передатчик и приемник. Заражение высокозащищенной сети может быть выполнено, что продемонстрировано
атаками с участием Stuxnet, Agent.Btz и других.

Из-за акустических свойств компьютерных вентиляторов данный метод применим и к другим типам вентиляторов (например, к вентиляторам графического процессора).

Тестовая среда состояла из компьютерного класса с обычными фоновый шум, семь рабочих станций, несколько сетевых коммутаторов и активная система кондиционирования воздуха.

Существует три основных категории контрмер: процедурные, программные и физические или аппаратные.
1) В процедурных контрмерах может быть использован подход зон
2) Программные меры противодействия включают использование защиты конечных точек для обнаружения злонамеренных действий на компьютере и вмешательство в API управления вентиляторами и доступ к шине. 
3) Аппаратные и физические меры противодействия могут включать детекторы шума, которые контролируют звуковую волну на определенной частоте или в диапазоне частот.

ИТОГИ
Вредоносное ПО может передавать информацию через воздушный зазор, передавая аудиосигналы с внутренних или внешних динамиков настольных компьютеров. В этой статье предлагается метод, использующий шум, издаваемый компьютерными вентиляторами, в качестве среды для эксфильтрации акустических данных.
Информация принимается смартфоном (или аналогичным устройством с микрофоном) с расстояния от нуля до восьми метров и со скоростью передачи данных до 15 бит в минуту. С помощью Fansmitter злоумышленники могут успешно передавать пароли и ключи шифрования с компьютера без динамиков с воздушным зазором на мобильный телефон, находящийся в той же комнате, с разных расстояний.

**Comment by almkuznetsov** [comment]
Как можно сформулировать название скрытого канала?

**Comment by almkuznetsov** [comment]
Добавил к каналу утечки телекоммуникационной информации за счет программного управления компонентами основных технических средств и систем с приемом акустической информации из воздушной среды
