### ISSUE TITLE
Mordechai Guri, Boris Zadov, Dima Bykhovsky, Yuval Elovici. PowerHammer: Exfiltrating data from  air-gapped computers through power lines. IEEE Transactions on Information Forensics and Security

### ISSUE THREAD

**Issue by nedomolkinaeyu** [almkuznetsov/bmstu-kb#66]

**Comment by nedomolkinaeyu** [comment]
Эксфильтрация данных из Air-Gapped. Компьютеры через линии электропередач.

PowerHammer, вредоносное ПО, использующее линии электропередач для извлечения данных с компьютеров с воздушным зазором. В этом случае вредоносный код, работающий на зараженном компьютере, может контролировать энергопотребление системы, намеренно регулируя загрузку процессора. Данные модулируются, кодируются и передаются поверх колебаний текущего потока, а затем передаются и распространяются по линиям электропередач. Это явление известно как «кондуктивное излучение». 

Атака состоит из четырех основных этапов: (1) заражение системы, (2) имплантация приемника, (3) сбор данных и (4) эксфильтрация данных.

КОНТРМЕРЫ
1. Контроль линий
2. Фильтрация сигнала
3. Заглушение сигнала
4. Обнаружение на основе хоста

ИТОГИ
Представляется две версии нападения. Мощный молот на линейном уровне: В этой атаке злоумышленник подключается к линиям электропередач в доме, которые непосредственно подключены к электрической розетке.Мощный удар на фазовом уровне: В этой атаке злоумышленник подключается к линиям электропередач на уровне фаз в главном электрощите. В обеих версиях атаки злоумышленник измеряет проводимую эмиссию, а затем декодирует эксфильтрованные данные.
Данные модулируются при колебаниях потребляемой мощности, а затем передаются от источника питания к линиям электропередач. В силовой молот на линейном уровне, злоумышленник помещает зонд на силовые кабели, питающие
компьютер. В силовой удар на фазовом уровне датчик размещен в главном электрощите всего этажа. Злоумышленник измеряет кондуктивное излучение в линиях электропередач, обрабатывает сигнал и декодирует его обратно в двоичную информацию.

**Comment by dpetruh** [comment]
Количество ядер, используемых при
передаче, напрямую влияет на энергопотребление
компьютера (т.е. большее количество передающих потоков приводит к большему
энергопотреблению) и, следовательно, на величину проводящего
излучения. Измерения на рисунке 15 показывают форму
переменного сигнала (’101010101010’), передаваемого с
ПК на частоте 10 кГц. Передачи в двух, четырех, шести и
восьми ядрах обеспечивают уровни сигнала 2,5 мА, 12 мА, 15 мА и
19 мА соответственно. Как можно видеть, количество ядер, используемых
для передач, коррелирует с проводимым излучением
измеренный. Однако важно отметить, что, хотя использование
большего количества ядер дает более сильный сигнал, злоумышленник может использовать только
часть доступных ядер для передач. Использование всех
ядер значительно повлияет на рабочую нагрузку в системе и
может выявить вредоносную активность.

**Comment by almkuznetsov** [comment]
Добавил к каналу утечки телекоммуникационной информации за счет программного управления компонентами основных технических средств и систем и побочных электромагнитных излучений с приемом информации контактно по линии
