### ISSUE TITLE
Mordechai Guri, Assaf Kachlon, Ofer Hasson, Gabi Kedma, Yisroel Mirsky, Yuval Elovici. GSMem: Data  Exfiltration from Air-Gapped Computers over {GSM} Frequencies. 24th {USENIX} Security Symposium  ({USENIX} Se-curity 15), 2015. 

### ISSUE THREAD

**Issue by nedomolkinaeyu** [almkuznetsov/bmstu-kb#67]
Эксфильтрация данных из Air-Gapped. Компьютеры на частотах GSM

Это вредоносное ПО, которое может передавать данные через воздушный зазор по сотовым частотам. Мошенническое программное обеспечение на зараженном целевом компьютере модулирует и передает электромагнитные сигналы на частотах сотовой связи, вызывая определенные инструкции, связанные с памятью, и используя многоканальную архитектуру памяти для усиления передачи. 

МОДЕЛЬ АТАКИ
Модель состязательной атаки является раздвоенной, поскольку она требует, чтобы зараженный компьютер служил в качестве передатчики зараженный мобильный телефон в качестве приемника.
Заражение компьютера в сети с воздушным зазором может быть выполнено, что продемонстрировано атаками с участием
Stuxnet, Agent.Btz и других.
Компрометация мобильного телефона может происходить с помощью социальной инженерии, вредоносных приложений,
USB-интерфейса или физического доступа. Когда скомпрометированный мобильный телефон оказывается рядом с зараженным компьютером, он может обнаруживать, принимать и декодировать любые передаваемые сигналы и
сохранять соответствующую полученную информацию. Позже телефон может передать данные злоумышленнику через
мобильные данные, SMS или Wi-Fi.

КОНТРМЕРЫ
С методом эксфильтрации, описанным в этой статье, подход «зон» может использоваться в качестве контрмеры, определяя
пространственные регионы, где мобильные телефоны, включая простые устройства, запрещены. Однако, как обсуждалось
ранее, дальность приема сигнала может увеличиваться при использовании специального аппаратного приемника. В этом
случае может помочь утепление перегородок.

Скрытый канал основан на электромагнитных волнах.

**Comment by almkuznetsov** [comment]
Добавил к каналу утечки телекоммуникационной информации за счет программного управления компонентами основных технических средств и систем и побочных электромагнитных излучений с приемом информации бесконтактно из диэлектрической воздушной среды
